# Rune costs are in gold nuggets.
# You must be in creative or have enough nuggets on you to cast a rune
RuneCosts:
  Teleport: 10
  Trap: 10
  Defense: 10
  Exploding: 10
  Healing: 10
  Wither_summoning: 10
  Speed: 10
  Hiding: 10